title: CFD <sup>3</sup> # The title of the blog
author: Mohsen Karimi # Your name 
email: mohsenk@outlook.com # your email shown in the footer
url: https://mohsen-debug.github.io/cfd-cubed/ # this is your site's root address.
description: > # this means to ignore newlines until "show_excerpts:"
  Nitty gritty stuff about CFD!
favicon: "./favicon.ico" # set the favicon of the site 

show_excerpts: false # set to true to show excerpts on the homepage
  
# Moving date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
moving:
  avatar_url: "/assets/imgs/avatar3.png" # avatar in about page
  about_you: # short description about you in about page
  date_format: "%b %d" # date format of posts in home page
  back_to: "Home" # In the post page, you have a back button above the title, you can custom the text by yourself.

# Build settings
# theme: moving # note, please use huangyz0918/moving if you want to publish to Github Pages.
remote_theme: huangyz0918/moving
plugins:
  - jekyll-remote-theme